apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-granite-granite-4-1-8b-autoresearch-v2-autoresearch
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./overlays/development
    repoURL: https://github.com/enterprisewebservice/ibm-granite-granite-4-1-8b-autoresearch-v2-autoresearch-gitops.git
    targetRevision: main
  destination:
    namespace: agent-office
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
